In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ironwolf437/laptop-price-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/nirmal/.cache/kagglehub/datasets/ironwolf437/laptop-price-dataset/versions/1

In [5]:
df=pd.read_csv("laptop_price.csv",encoding='UTF-8',sep=',')
df.head()

,Company,Product,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [6]:
df.columns

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Company              1275 non-null   object
 1   Product              1275 non-null   object
 2   TypeName             1275 non-null   object
 3   Inches               1275 non-null   float64
 4   ScreenResolution     1275 non-null   object
 5   CPU_Company          1275 non-null   object
 6   CPU_Type             1275 non-null   object
 7   CPU_Frequency (GHz)  1275 non-null   float64
 8   RAM (GB)             1275 non-null   int64
 9   Memory               1275 non-null   object
 10  GPU_Company          1275 non-null   object
 11  GPU_Type             1275 non-null   object
 12  OpSys                1275 non-null   object
 13  Weight (kg)          1275 non-null   float64
 14  Price (Euro)         1275 non-null   float64
dtypes: float64(4), int64(1), object(10)
memory usage: 149.5+ KB

In [ ]:
#pre-processing
df.isna().sum()

# df.dropna(inplace=True)

Company                0
Product                0
TypeName               0
Inches                 0
ScreenResolution       0
CPU_Company            0
CPU_Type               0
CPU_Frequency (GHz)    0
RAM (GB)               0
Memory                 0
GPU_Company            0
GPU_Type               0
OpSys                  0
Weight (kg)            0
Price (Euro)           0
dtype: int64

In [14]:
df.columns

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)'],
      dtype='object')

In [15]:
df2=df[['TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)']]

df2.head()

,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,2.3,8,128GB SSD,Intel,Iris Plus Graphics 640,macOS,1.37,1339.69
1,Ultrabook,13.3,1440x900,Intel,Core i5,1.8,8,128GB Flash Storage,Intel,HD Graphics 6000,macOS,1.34,898.94
2,Notebook,15.6,Full HD 1920x1080,Intel,Core i5 7200U,2.5,8,256GB SSD,Intel,HD Graphics 620,No OS,1.86,575.00
3,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel,Core i7,2.7,16,512GB SSD,AMD,Radeon Pro 455,macOS,1.83,2537.45
4,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel,Core i5,3.1,8,256GB SSD,Intel,Iris Plus Graphics 650,macOS,1.37,1803.60

In [18]:
from sklearn.preprocessing import LabelEncoder
columns_to_be_encoded=['TypeName', 'ScreenResolution','CPU_Company', 'CPU_Type', 'Memory','GPU_Company', 'GPU_Type', 'OpSys']

# #encode columns
# for column in columns_to_be_encoded:
#     df2[column]=df2[column].astype('category').cat.codes

# df2.head()

for column in columns_to_be_encoded:
    encoder=LabelEncoder()
    df2[column]=encoder.fit_transform(df2[column])

df2.head()

/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])
/var/folders/f0/8zss9bcx2pq3p607h6tvt1sr0000gn/T/ipykernel_5288/3284013062.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[column]=encoder.fit_transform(df2[column])

,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg),Price (Euro)
0,4,13.3,23,1,40,2.3,8,4,2,56,8,1.37,1339.69
1,4,13.3,1,1,40,1.8,8,2,2,50,8,1.34,898.94
2,3,15.6,8,1,46,2.5,8,16,2,52,4,1.86,575.00
3,4,15.4,25,1,54,2.7,16,29,0,76,8,1.83,2537.45
4,4,13.3,23,1,40,3.1,8,16,2,57,8,1.37,1803.60

In [19]:
#split the data
from sklearn.model_selection import train_test_split
X=df2.drop('Price (Euro)',axis=1)
Y=df2['Price (Euro)']

X

,TypeName,Inches,ScreenResolution,CPU_Company,CPU_Type,CPU_Frequency (GHz),RAM (GB),Memory,GPU_Company,GPU_Type,OpSys,Weight (kg)
0,4,13.3,23,1,40,2.3,8,4,2,56,8,1.37
1,4,13.3,1,1,40,1.8,8,2,2,50,8,1.34
2,3,15.6,8,1,46,2.5,8,16,2,52,4,1.86
3,4,15.4,25,1,54,2.7,16,29,0,76,8,1.83
4,4,13.3,23,1,40,3.1,8,16,2,57,8,1.37
...,...,...,...,...,...,...,...,...,...,...,...,...
1270,0,14.0,13,1,55,2.5,4,4,2,46,5,1.80
1271,0,13.3,19,1,55,2.5,16,29,2,46,5,1.30
1272,3,14.0,0,1,20,1.6,2,35,2,39,5,1.50
1273,3,15.6,0,1,55,2.5,6,10,0,88,5,2.19
1274,3,15.6,0,1,20,1.6,4,26,2,39,5,2.20

In [21]:
Y

0       1339.69
1        898.94
2        575.00
3       2537.45
4       1803.60
         ...
1270     638.00
1271    1499.00
1272     229.00
1273     764.00
1274     369.00
Name: Price (Euro), Length: 1275, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)